install apple-gcc42
install cloc
install couchdb
install cryptopp
install ctags
install dart
install dnstop
install elasticsearch
install elixir
install ffmpeg
install figlet
install fontconfig
install freetds
install gawk
install gd
install ghostscript
install git
install glib
install gnu-tar
install go
install gource
install graphviz
install gsl
install gti
install id3lib
install imagemagick
install intltool
install leiningen
install libidn
install libksba
install libmagic
install libxslt
install libyaml
install lua
install memcached
install mercurial
install mongodb
install mp3info
install mp3val
install mp3wrap
install msgpack
install mtr
install mysql
install node
install nvm
install objective-caml
install p11-kit
install p7zip
install phantomjs
install pianobar
install postgresql
install qt
install ranger
install redis
install rust
install sl
install sqlite
install tmux
install tree
install unrar
install upx
install valgrind
install vim
install watch
install wget
install zeromq
install zsh
install zsh-completions
