install cloc
install cryptopp
install ctags
install dnstop
install elasticsearch
install ffmpeg
install figlet
install fontconfig
install gawk
install gd
install ghostscript
install git
install glib
install gnu-tar
install go
install graphviz
install gsl
install gti
install id3lib
install imagemagick
install intltool
install leiningen
install libidn
install libksba
install libmagic
install libxslt
install libyaml
install lua
install memcached
install mercurial
install mongodb
install mp3info
install mp3val
install mp3wrap
install msgpack
install mtr
install mysql
install node
install nvm
install p11-kit
install p7zip
install phantomjs
install pianobar
install postgresql
install ranger
install redis
install sl
install sqlite
install tmux
install tree
install unrar
install upx
install valgrind
install vim
install watch
install wget
install zeromq
install zsh
install zsh-completions
